# Generated by Django 3.0 on 2020-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Fake_username',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
